let tabla=[];const docView=document.getElementById('docView');const contenedorTabla=document.getElementById('contenedorTabla');
window.onload=function(){cargarDatosGuardados();if(tabla.length==0){crearTablaVacia(20,8)}renderTabla();}
function cambiarVista(v){document.getElementById('tabDoc').classList.remove('active');document.getElementById('tabSheet').classList.remove('active');document.getElementById('ribbonDoc').style.display='none';document.getElementById('ribbonSheet').style.display='none';document.getElementById('docView').style.display='none';document.getElementById('sheetView').style.display='none';if(v=='doc'){document.getElementById('tabDoc').classList.add('active');document.getElementById('ribbonDoc').style.display='block';document.getElementById('docView').style.display='block';}else{document.getElementById('tabSheet').classList.add('active');document.getElementById('ribbonSheet').style.display='block';document.getElementById('sheetView').style.display='block';}}
function aplicarEstilo(c){document.execCommand(c,false,null);docView.focus();}
function aplicarTamano(s){document.execCommand('fontSize',false,s);docView.focus();}
function aplicarColor(c){document.execCommand('foreColor',false,c);docView.focus();}
function saveAll(){const h=docView.innerHTML;localStorage.setItem('o_doc',h);localStorage.setItem('o_doc_backup',h);localStorage.setItem('o_sheet',JSON.stringify(tabla));localStorage.setItem('o_sheet_backup',JSON.stringify(tabla));document.getElementById('saveStatus').innerText='¡GUARDADO! '+new Date().toLocaleTimeString();setTimeout(()=>document.getElementById('saveStatus').innerText='LISTO - OFFLINE',2000);}
function cargarDatosGuardados(){let d=localStorage.getItem('o_doc_backup')||localStorage.getItem('o_doc');if(d)docView.innerHTML=d;let s=localStorage.getItem('o_sheet_backup')||localStorage.getItem('o_sheet');if(s){try{tabla=JSON.parse(s);renderTabla();}catch(e){}}if(tabla.length==0){crearTablaVacia(20,8);renderTabla();}document.getElementById('saveStatus').innerText='DATOS RESTAURADOS 👁️';setTimeout(()=>document.getElementById('saveStatus').innerText='LISTO - OFFLINE',1500);}
function crearNuevo(){if(confirm('¿Borrar doc? Se respalda')){localStorage.setItem('o_doc_backup',docView.innerHTML);docView.innerHTML='Escribe aquí tu documento...';saveAll();}}
function crearNuevoSheet(){if(confirm('¿Borrar hoja? Se respalda')){localStorage.setItem('o_sheet_backup',JSON.stringify(tabla));crearTablaVacia(20,8);renderTabla();saveAll();}}
function copiarDocumento(){navigator.clipboard.writeText(docView.innerText);alert('Copiado')}
function exportarPDF(){window.print();}
function exportarExcel(){let csv=tabla.map(r=>r.join(',')).join('\n');let b=new Blob([csv],{type:'text/csv'});let a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='hoja.csv';a.click();}
function crearTablaVacia(f,c){tabla=[];for(let i=0;i<f;i++){let r=[];for(let j=0;j<c;j++)r.push('');tabla.push(r);}}
function renderTabla(){let h='<table id="tablaDatos"><tr><th></th>';for(let c=0;c<tabla[0].length;c++)h+=`<th>${String.fromCharCode(65+c)}</th>`;h+='</tr>';for(let r=0;r<tabla.length;r++){h+=`<tr><th>${r+1}</th>`;for(let cc=0;cc<tabla[r].length;cc++){h+=`<td contenteditable="true" oninput="tabla[${r}][${cc}]=this.innerText">${tabla[r][cc]}</td>`;}h+='</tr>';}h+='</table>';contenedorTabla.innerHTML=h;}
function insertarNuevaHoja(){tabla.push(new Array(tabla[0].length).fill(''));renderTabla();}
function generarGraficaLocal(){document.getElementById('graficaWrap').style.display='block';const ctx=document.getElementById('miGrafica').getContext('2d');ctx.clearRect(0,0,400,200);ctx.fillStyle='#2b579a';let nums=tabla.flat().map(v=>parseFloat(v)).filter(n=>!isNaN(n)).slice(0,10);if(nums.length==0)nums=[5,10,15,8,12];let mx=Math.max(...nums);nums.forEach((n,i)=>{ctx.fillRect(i*35+10,190-(n/mx*150),25,(n/mx*150));});}
